"""V2-21: STATE_DSN, fail-closed migrations, health ping, export checksums, dual-engine."""

from __future__ import annotations

import os
import re
from datetime import datetime
from pathlib import Path

import pytest

from ledger import SchemaTooNew, SqliteLedgerStore, StoreConfigError, load_store_config, migrate
from ledger.export import checksum_lines, row_line
from ledger.migrate import CODE_SCHEMA_VERSION, list_dialect_files, list_migration_files
from ledger.postgres import is_postgres_dsn, redact_dsn, rewrite_sql_for_postgres, split_sql

REPO = Path(__file__).resolve().parents[3]
NOW = datetime.fromisoformat("2026-09-28T10:00:00+05:30")
DROP_COL = re.compile(r"\bDROP\s+COLUMN\b|\bRENAME\s+COLUMN\b", re.IGNORECASE)


def _pg_dsn() -> str:
    return (os.environ.get("STATE_DSN") or "").strip()


def _require_pg() -> str:
    dsn = _pg_dsn()
    if not dsn or not is_postgres_dsn(dsn):
        pytest.skip("STATE_DSN unset (sqlite-only unit job)")
    pytest.importorskip("psycopg")
    return dsn


def _reset_pg(dsn: str) -> None:
    from ledger.postgres import connect_postgres

    conn = connect_postgres(dsn)
    try:
        conn.execute("DROP SCHEMA public CASCADE")
        conn.execute("CREATE SCHEMA public")
    finally:
        conn.close()


def _envelope() -> object:
    from types import SimpleNamespace

    return SimpleNamespace(
        event_id="evt_v221",
        stream="md:clock",
        event_type="CLOCK",
        available_ts=NOW.isoformat(),
        payload={"seq": 1},
    )


def test_shared_migrations_exclude_dialect_files() -> None:
    names = [f.name for f in list_migration_files()]
    assert names == ["001_core.sql", "002_v2_core.sql", "003_entry_plan_payload.sql"]
    dialect = [f.name for f in list_dialect_files("pg")]
    assert "002_v2_core.pg.sql" in dialect
    assert all(not n.endswith(".pg.sql") for n in names)


def test_migrations_expand_contract_only() -> None:
    for path in list_migration_files():
        text = path.read_text(encoding="utf-8")
        assert DROP_COL.search(text) is None, path.name


def test_rewrite_autoincrement_and_split_dollar_quotes() -> None:
    sql = "id INTEGER PRIMARY KEY AUTOINCREMENT"
    assert "GENERATED BY DEFAULT AS IDENTITY" in rewrite_sql_for_postgres(sql)
    assert "CREATE OR REPLACE VIEW" in rewrite_sql_for_postgres("CREATE VIEW IF NOT EXISTS daily_pnl AS SELECT 1")
    body = "CREATE FUNCTION f() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'x'; END; $$ LANGUAGE plpgsql;"
    parts = split_sql(body)
    assert len(parts) == 1 and "RAISE EXCEPTION" in parts[0]


def test_postgres_engine_without_dsn_is_refused() -> None:
    with pytest.raises(StoreConfigError, match="STATE_DSN"):
        load_store_config(environ={"STATE_ENGINE": "postgres"}, yaml_path=REPO / "config" / "v2" / "store.yaml")


def test_state_dsn_selects_postgres_engine() -> None:
    cfg = load_store_config(
        environ={"STATE_DSN": "postgresql://aad:aad@127.0.0.1:5432/aad_ledger"},
        yaml_path=REPO / "config" / "v2" / "store.yaml",
    )
    assert cfg.engine == "postgres"
    assert is_postgres_dsn(cfg.dsn)
    redacted = redact_dsn(cfg.dsn)
    assert "***" in redacted and "127.0.0.1" in redacted and ":aad@" not in redacted


def test_default_engine_is_sqlite() -> None:
    cfg = load_store_config(environ={}, yaml_path=REPO / "config" / "v2" / "store.yaml")
    assert cfg.engine == "sqlite"
    assert cfg.sqlite_path == "data/state/aad.sqlite"


def test_sqlite_health_ping_and_protocol(tmp_path: Path) -> None:
    store = SqliteLedgerStore(tmp_path / "aad.sqlite", migrate_schema=True)
    ping = store.health_ping()
    assert ping == {"ok": True, "engine": "sqlite", "schema_version": CODE_SCHEMA_VERSION}
    env = _envelope()
    with store.transaction():
        store.checkpoint(env)  # type: ignore[arg-type]
    assert store.get_last_checkpoint() is not None
    drained = store.drain_outbox()
    assert len(drained) == 1 and drained[0]["event_id"] == "evt_v221"
    store.upsert_position_v2("founder", "NSE_FNO:NIFTY:2026-09-29:24400:CE", 65, "100.00", strategy_id="TEST")
    rows = store.positions_v2()
    assert rows[0]["net_qty"] == 65 and rows[0]["strategy_id"] == "TEST"
    store.close()


def test_checksum_is_stable() -> None:
    cols = ["a", "b"]
    line = row_line(cols, {"a": 1, "b": None})
    assert line == "1|NULL"
    assert checksum_lines([line]) == checksum_lines(["1|NULL"])
    assert checksum_lines([line]) != checksum_lines(["1|0"])


def test_cli_migrate_sqlite(tmp_path: Path) -> None:
    from ledger.__main__ import main

    db = tmp_path / "aad.sqlite"
    assert main(["migrate", "--path", str(db)]) == 0
    store = SqliteLedgerStore(db)
    assert store.health_ping()["ok"] is True
    store.close()


def test_cli_ping_sqlite(tmp_path: Path) -> None:
    from ledger.__main__ import main

    db = tmp_path / "aad.sqlite"
    assert main(["ping", "--path", str(db)]) == 0


def test_migrate_failure_does_not_record_version(tmp_path: Path) -> None:
    db = tmp_path / "aad.sqlite"
    migrate(db)
    bad = tmp_path / "099_bad.sql"
    bad.write_text("CREATE TABLE broken (id INTEGER PRIMARY KEY);\nTHIS IS NOT SQL;\n", encoding="utf-8")
    from ledger.migrate import list_migration_files, version_of

    files = [*list_migration_files(), bad]
    with pytest.raises(Exception):
        migrate(db, files=files)
    store = SqliteLedgerStore(db)
    assert store.schema_version < version_of(bad) or store.schema_version == CODE_SCHEMA_VERSION
    assert store.schema_version == CODE_SCHEMA_VERSION
    store.close()


def test_postgres_store_refuses_non_dsn() -> None:
    from ledger.postgres import PostgresLedgerStore

    with pytest.raises(StoreConfigError, match="STATE_DSN"):
        PostgresLedgerStore("data/state/aad.sqlite")


def test_dual_engine_checkpoint_outbox_positions() -> None:
    dsn = _require_pg()
    from ledger.postgres import PostgresLedgerStore

    _reset_pg(dsn)
    store = PostgresLedgerStore(dsn, migrate_schema=True)
    try:
        ping = store.health_ping()
        assert ping["ok"] is True and ping["engine"] == "postgres"
        assert ping["schema_version"] == CODE_SCHEMA_VERSION
        env = _envelope()
        with store.transaction():
            store.checkpoint(env)  # type: ignore[arg-type]
        assert store.get_last_checkpoint() is not None
        drained = store.drain_outbox()
        assert len(drained) == 1 and drained[0]["event_id"] == "evt_v221"
        assert store.drain_outbox() == []
        store.upsert_position_v2("founder", "NSE_FNO:NIFTY:2026-09-29:24400:CE", 65, "100.00", strategy_id="TEST")
        rows = store.positions_v2()
        assert int(rows[0]["net_qty"]) == 65 and rows[0]["strategy_id"] == "TEST"
    finally:
        store.close()


def test_postgres_refuses_newer_schema() -> None:
    dsn = _require_pg()
    from ledger.postgres import PostgresLedgerStore, connect_postgres

    _reset_pg(dsn)
    store = PostgresLedgerStore(dsn, migrate_schema=True)
    store.close()
    conn = connect_postgres(dsn)
    try:
        conn.execute("INSERT INTO schema_version (version, applied_at) VALUES (99, %s)", (NOW.isoformat(),))
    finally:
        conn.close()
    with pytest.raises(SchemaTooNew):
        PostgresLedgerStore(dsn)


def test_export_sqlite_to_postgres_checksums(tmp_path: Path) -> None:
    dsn = _require_pg()
    from ledger.export import export_sqlite_to_postgres

    db = tmp_path / "aad.sqlite"
    store = SqliteLedgerStore(db, migrate_schema=True)
    env = _envelope()
    with store.transaction():
        store.checkpoint(env)  # type: ignore[arg-type]
    store.upsert_position_v2("founder", "NSE_FNO:NIFTY:2026-09-29:24400:CE", 65, "100.00", strategy_id="TEST")
    store.close()
    _reset_pg(dsn)
    report = export_sqlite_to_postgres(db, dsn)
    assert report["ok"] is True
    assert report["tables"]["positions_v2"]["count"] == 1
    assert report["tables"]["engine_checkpoint"]["count"] == 1
    assert report["tables"]["outbox"]["count"] == 1
    with pytest.raises(Exception, match="refuse overwrite|already has"):
        export_sqlite_to_postgres(db, dsn)


def test_cli_export_refuses_without_dsn(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    from ledger.__main__ import main

    monkeypatch.delenv("STATE_DSN", raising=False)
    monkeypatch.delenv("STATE_ENGINE", raising=False)
    with pytest.raises(StoreConfigError, match="STATE_DSN"):
        main(["export", "--to", "postgres", "--from", str(tmp_path / "x.sqlite")])
