"""Canonical replay dumps, committed synthetic fixtures and the dual-tape writer.

``canonical_dump(board)`` is what "the same result" means for goldens and for the owner's offline
replay: sorted-key JSON of per-index totals, every closed trade's defining fields (floats rounded to
6 places) and the skip-reason counts. Wall-clock fields are excluded.

Fixtures are synthetic only (``event_parity.synthetic_triples``): never market data. Each fixture
file is regenerated byte-for-byte by ``build_fixture`` so CI can prove it was not hand-edited.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Optional, Sequence

from desk_ml.event_parity import SYNTHETIC_SHAPE, TRIPLE_FIELDS, synthetic_triples, write_fixture
from desk_ml.features import Triple

IST = timezone(timedelta(hours=5, minutes=30))
FIXTURE_DIR = Path(__file__).resolve().parents[3] / "tests" / "fixtures"
GOLDEN_DIR = Path(__file__).resolve().parents[3] / "tests" / "golden"
TRADE_KEYS = (
    "trade_id", "book_id", "underlying", "side", "atm_strike", "opened_ts", "closed_ts", "entry", "exit", "qty",
    "lots", "exit_reason", "gross_pnl_inr", "charges_inr", "realized_pnl_inr", "filled",
)
LOT_SIZES = {"NIFTY": 65, "BANKNIFTY": 30, "SENSEX": 20}
SYNTHETIC_SHAPE.setdefault("BANKNIFTY", (55000.0, 2.2, 100, 300))

# name -> (underlyings, seed, step seconds). Seeds chosen so each fixture actually trades.
FIXTURES: dict[str, tuple[tuple[str, ...], int, int]] = {
    "syn_multi_3idx_s5": (("NIFTY", "BANKNIFTY", "SENSEX"), 5, 30),
    "syn_nifty_live_s23": (("NIFTY",), 23, 60),
}
LEGACY_FIXTURE = "synthetic_session_nifty"  # event_parity.write_fixture, seed 23, 20 s
DAY = "2026-09-10"


def _num(v: Any) -> Any:
    if isinstance(v, bool) or v is None:
        return v
    if isinstance(v, float):
        return round(v, 6)
    return v


def canonical_trade(row: dict[str, Any]) -> dict[str, Any]:
    return {k: _num(row.get(k)) for k in TRADE_KEYS}


def canonical_dump(board: dict[str, Any]) -> bytes:
    closed = [canonical_trade(r) for r in board.get("closed_trades") or []]
    closed.sort(key=lambda r: (str(r["underlying"]), int(r["opened_ts"] or 0), str(r["trade_id"])))
    per: dict[str, dict[str, Any]] = {}
    for r in closed:
        if not r["filled"]:
            continue
        d = per.setdefault(str(r["underlying"]), {"n_trades": 0, "net": 0.0, "gross": 0.0, "charges": 0.0})
        d["n_trades"] += 1
        d["net"] += float(r["realized_pnl_inr"] or 0.0)
        d["gross"] += float(r["gross_pnl_inr"] or 0.0)
        d["charges"] += float(r["charges_inr"] or 0.0)
    per = {u: {k: _num(v) for k, v in d.items()} for u, d in per.items()}
    blob = {"per_index": per, "closed_trades": closed, "skip_reason_counts": board.get("skip_reason_counts") or {}}
    return (json.dumps(blob, sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8")


def summary(board: dict[str, Any]) -> dict[str, Any]:
    filled = [r for r in board.get("closed_trades") or [] if r.get("filled")]
    return {"n_trades": len(filled), "net_pnl_inr": round(sum(float(r.get("realized_pnl_inr") or 0) for r in filled), 2)}


# ------------------------------------------------------------------ fixtures


def fixture_triples(name: str) -> dict[str, list[Triple]]:
    unds, seed, step = FIXTURES[name]
    return {u: synthetic_triples(day=DAY, seed=seed + k, step_s=step, underlying=u) for k, u in enumerate(unds)}


def build_fixture(name: str) -> bytes:
    by_und = fixture_triples(name)
    rows = {u: [[getattr(t, f) for f in TRIPLE_FIELDS] for t in tr] for u, tr in by_und.items()}
    digest = hashlib.sha256(json.dumps(rows, separators=(",", ":")).encode()).hexdigest()
    unds, seed, step = FIXTURES[name]
    blob = {
        "synthetic": True, "generator": "desk_ml.testing.canonical", "version": 1, "name": name, "seed": seed,
        "step_s": step, "session_ist_date": DAY, "note": "Synthetic sessions. Not market data.",
        "lot_sizes": {u: LOT_SIZES[u] for u in unds}, "fields": list(TRIPLE_FIELDS), "rows": rows,
        "sha256_of_triples": digest,
    }
    return (json.dumps(blob, separators=(",", ":")) + "\n").encode("utf-8")


def build_legacy_fixture() -> bytes:
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "f.json"
        write_fixture(path)
        return path.read_bytes()


def load_fixture(name: str, folder: Optional[Path] = None) -> dict[str, Any]:
    folder = folder or FIXTURE_DIR
    blob = json.loads((folder / f"{name}.json").read_text(encoding="utf-8"))
    if name == LEGACY_FIXTURE:
        by_und = {blob["underlying"]: [Triple(**dict(zip(blob["fields"], r))) for r in blob["rows"]]}
        return {"triples": by_und, "lot_sizes": {blob["underlying"]: blob["lot_size"]}, "day": blob["session_ist_date"]}
    by_und = {u: [Triple(**dict(zip(blob["fields"], r))) for r in rows] for u, rows in blob["rows"].items()}
    return {"triples": by_und, "lot_sizes": blob["lot_sizes"], "day": blob["session_ist_date"]}


def regenerate_all(folder: Optional[Path] = None) -> dict[str, bytes]:
    folder = folder or FIXTURE_DIR
    out = {f"{LEGACY_FIXTURE}.json": build_legacy_fixture()}
    for name in FIXTURES:
        out[f"{name}.json"] = build_fixture(name)
    return out


# ------------------------------------------------------------------ goldens

# A copy of the box's production params (not the code defaults): the legacy replay reads them.
PARAMS_LEGACY = {"stop_frac": 0.38, "scalp_hold_bars": 9, "nudge_n_closed": 494}
GOLDEN_FIXTURES = (LEGACY_FIXTURE, *FIXTURES)


def golden_dump(name: str, *, flag: str = "off") -> bytes:
    """Legacy flag-off (or flag-on, replay risk file) replay of a committed fixture, canonical bytes.

    Founder JSON file (no command log) and a params file in a scratch root, live_session=True:
    the same inputs the owner's offline replay uses. Also importable against main's code.
    """
    import tempfile

    import desk_ml.paper_scalp as ps

    fx = load_fixture(name)
    saved = ps.load_index_closes, ps.resolve_lot_size
    ps.load_index_closes = lambda u, root=None: {}
    ps.resolve_lot_size = lambda und, root=None: (int(fx["lot_sizes"].get(und, LOT_SIZES[und])), "fixture")
    try:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            recon = root / "data" / "recon"
            recon.mkdir(parents=True)
            (recon / "founder_trade_underlyings.json").write_text(json.dumps({"trade_underlyings": list(fx["triples"])}))
            (recon / "ml_paper_session_params.json").write_text(json.dumps(PARAMS_LEGACY))
            kw = dict(root=root, underlyings=tuple(fx["triples"]), triples_by_und=fx["triples"],
                      session_ist_date=fx["day"], write=False, live_session=True)
            if flag == "on":
                from desk_ml.event_path import EventSession

                session = EventSession()
                try:
                    board = ps.replay_paper_scalp(**kw, event_session=session)
                finally:
                    session.close()
            else:
                board = ps.replay_paper_scalp(**kw, use_event_bus=False)
    finally:
        ps.load_index_closes, ps.resolve_lot_size = saved
    return canonical_dump(board)


# ------------------------------------------------------------------ dual-tape JSONL


def snap_row(und: str, t: Triple) -> dict[str, Any]:
    """One underlying's dual-tape snap, as ``persist_tick`` writes it (enough for the loader)."""
    return {
        "underlying": und, "index_ltp": t.idx_close, "atm_strike": t.atm_strike,
        "atm_ce_ltp": t.ce_close, "atm_pe_ltp": t.pe_close,
        "itm_ce_ltp": t.itm_ce_close, "itm_pe_ltp": t.itm_pe_close,
        "itm_ce_strike": t.itm_ce_strike, "itm_pe_strike": t.itm_pe_strike,
        "index_volume": t.idx_volume, "premium_kind": t.premium_kind,
    }


def tape_lines(triples_by_und: dict[str, Sequence[Triple]]) -> list[tuple[int, str]]:
    """(ts, JSONL line) per tick, every underlying of that tick in one line, time ordered."""
    by_ts: dict[int, list[dict[str, Any]]] = {}
    for und, triples in triples_by_und.items():
        for t in triples:
            by_ts.setdefault(int(t.ts), []).append(snap_row(und, t))
    out = []
    for ts in sorted(by_ts):
        line = {"as_of_ist": datetime.fromtimestamp(ts, IST).isoformat(timespec="seconds"), "underlyings": by_ts[ts]}
        out.append((ts, json.dumps(line, separators=(",", ":"))))
    return out


def main(argv: Optional[Sequence[str]] = None) -> int:
    """python -m desk_ml.testing.canonical [--write | --write-goldens]  (fixture provenance / goldens)."""
    import argparse

    ap = argparse.ArgumentParser(prog="python -m desk_ml.testing.canonical")
    ap.add_argument("--write", action="store_true", help="rewrite the committed fixtures from the generator")
    ap.add_argument("--write-goldens", action="store_true", help="rewrite tests/golden/*.legacy.json (say why in the PR)")
    args = ap.parse_args(argv)
    if args.write_goldens:
        GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
        for name in GOLDEN_FIXTURES:
            (GOLDEN_DIR / f"{name}.legacy.json").write_bytes(golden_dump(name))
            print(f"wrote {name}.legacy.json")
        return 0
    bad = []
    for fname, data in regenerate_all().items():
        path = FIXTURE_DIR / fname
        if args.write:
            path.write_bytes(data)
        elif not path.is_file() or path.read_bytes() != data:
            bad.append(fname)
    for fname in bad:
        print(f"FIXTURE MISMATCH: {fname} is not what the generator produces (hand-edited or stale)")
    print("fixtures OK" if not bad else f"{len(bad)} fixture(s) differ")
    return 1 if bad else 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
