#!/usr/bin/env python3
"""Counsel loop runner for DESK_SIGNAL_JSON spec. Research helper, not a job.

Runs one panel round (Gemini + OpenAI) on the current spec draft and saves the
raw texts under data/recon/. No orders. No signals generated by counsel.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "packages" / "trading_agents_india" / "src"))

from trading_agents_india.counsel import complete_panel  # noqa: E402

OUT = Path(__file__).resolve().parents[1] / "data" / "recon"


def run(round_no: int, prompt: str, facts: str) -> dict:
    result = complete_panel(prompt, role="review", facts=facts)
    stamp = datetime.now().strftime("%H%M%S")
    path = OUT / f"COUNSEL_SIGNAL_FORMAT_r{round_no}_{stamp}.json"
    path.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"saved {path}")
    print("together:", result.get("together"))
    for who in ("gemini", "openai"):
        pane = result["panel"][who]
        print(f"\n===== {who} ok={pane['ok']} =====")
        print(pane["text"][:3000])
    return result


if __name__ == "__main__":
    round_no = int(sys.argv[1])
    prompt_file = Path(sys.argv[2])
    facts_file = Path(sys.argv[3])
    run(round_no, prompt_file.read_text(encoding="utf-8"), facts_file.read_text(encoding="utf-8"))
