"""V2-21 Postgres LedgerStore. Paper only. Fail-closed. No live broker."""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

import yaml  # type: ignore[import-untyped]

from ledger.migrate import (
    CODE_SCHEMA_VERSION,
    SchemaTooNew,
    list_dialect_files,
    list_migration_files,
    version_of,
)
from ledger.store import IST, iso_ist
from ledger.v2 import CheckpointEnvelope, money_sql

_PG_PREFIX = ("postgres://", "postgresql://")
_DUP_COL = re.compile(r"already exists", re.IGNORECASE)
_STORE_YAML = Path("config/v2/store.yaml")


class StoreConfigError(RuntimeError):
    """Missing DSN, bad engine, connect/ping failure. Refuse to start."""


@dataclass(frozen=True)
class StoreConfig:
    engine: str
    dsn: str
    sqlite_path: str


def redact_dsn(dsn: str) -> str:
    return re.sub(r"(://[^:/]+:)[^@]+(@)", r"\1***\2", dsn)


def is_postgres_dsn(dsn: str) -> bool:
    return dsn.startswith(_PG_PREFIX)


def _store_yaml_path() -> Path:
    here = Path(__file__).resolve()
    for parent in here.parents:
        cand = parent / "config" / "v2" / "store.yaml"
        if cand.is_file():
            return cand
    return _STORE_YAML


def load_store_config(
    *,
    environ: dict[str, str] | None = None,
    yaml_path: Path | None = None,
) -> StoreConfig:
    env = environ if environ is not None else os.environ
    dsn = (env.get("STATE_DSN") or "").strip()
    data: dict[str, Any] = {}
    path = yaml_path if yaml_path is not None else _store_yaml_path()
    if path.is_file():
        loaded = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if isinstance(loaded, dict):
            data = loaded
    engine = str(env.get("STATE_ENGINE") or data.get("engine") or "sqlite").strip().lower()
    sqlite_path = str(data.get("sqlite_path") or "data/state/aad.sqlite")
    if dsn and is_postgres_dsn(dsn):
        engine = "postgres"
    elif dsn and engine == "sqlite":
        sqlite_path = dsn.removeprefix("sqlite:///")
    if engine in {"pg", "postgresql"}:
        engine = "postgres"
    if engine not in {"sqlite", "postgres"}:
        raise StoreConfigError(f"unknown store engine {engine!r}")
    if engine == "postgres" and not is_postgres_dsn(dsn):
        raise StoreConfigError("postgres engine requires STATE_DSN")
    return StoreConfig(engine=engine, dsn=dsn, sqlite_path=sqlite_path)


def rewrite_sql_for_postgres(sql: str) -> str:
    """Shared-subset SQL → Postgres. 001/002 sqlite-isms only."""
    out = re.sub(
        r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        sql,
        flags=re.IGNORECASE,
    )
    out = re.sub(r"CREATE\s+VIEW\s+IF\s+NOT\s+EXISTS", "CREATE OR REPLACE VIEW", out, flags=re.IGNORECASE)
    return re.sub(r"ROUND\(([^,]+),\s*(\d+)\)", r"ROUND((\1)::numeric, \2)", out, flags=re.IGNORECASE)


def split_sql(sql: str) -> list[str]:
    """Split on `;` outside `--` comments and `$$` dollar quotes (plpgsql)."""
    lines: list[str] = []
    for line in sql.splitlines():
        cut = line.find("--")
        lines.append(line if cut < 0 else line[:cut])
    text = "\n".join(lines)
    parts: list[str] = []
    buf: list[str] = []
    i = 0
    in_dollar = False
    while i < len(text):
        if text.startswith("$$", i):
            in_dollar = not in_dollar
            buf.append("$$")
            i += 2
            continue
        if text[i] == ";" and not in_dollar:
            stmt = "".join(buf).strip()
            if stmt:
                parts.append(stmt)
            buf = []
            i += 1
            continue
        buf.append(text[i])
        i += 1
    tail = "".join(buf).strip()
    if tail:
        parts.append(tail)
    return parts


def _require_psycopg() -> Any:
    try:
        import psycopg
    except ImportError as exc:
        raise StoreConfigError("psycopg is required for the postgres engine") from exc
    return psycopg


def connect_postgres(dsn: str) -> Any:
    if not is_postgres_dsn(dsn):
        raise StoreConfigError("postgres engine requires STATE_DSN")
    psycopg = _require_psycopg()
    from psycopg.rows import dict_row

    try:
        return psycopg.connect(dsn, autocommit=True, row_factory=dict_row)
    except Exception as exc:
        raise StoreConfigError(f"postgres connect failed: {redact_dsn(dsn)}") from exc


def current_version_pg(conn: Any) -> int:
    row = conn.execute(
        "SELECT 1 AS ok FROM information_schema.tables WHERE table_schema='public' AND table_name='schema_version'"
    ).fetchone()
    if row is None:
        return 0
    got = conn.execute("SELECT COALESCE(MAX(version), 0) AS v FROM schema_version").fetchone()
    return int(got["v"] if got else 0)


def check_schema_pg(conn: Any, *, code_version: int = CODE_SCHEMA_VERSION) -> int:
    ver = current_version_pg(conn)
    if ver > code_version:
        raise SchemaTooNew(f"schema_version {ver} > code {code_version}; refuse to start")
    return ver


def _apply_sql_pg(conn: Any, sql: str) -> None:
    for stmt in split_sql(sql):
        conn.execute("SAVEPOINT mig")
        try:
            conn.execute(stmt)
            conn.execute("RELEASE SAVEPOINT mig")
        except Exception as exc:
            conn.execute("ROLLBACK TO SAVEPOINT mig")
            if stmt.upper().lstrip().startswith("ALTER") and _DUP_COL.search(str(exc)):
                continue
            raise


def _record_version_pg(conn: Any, version: int) -> None:
    stamp = datetime.now(IST).isoformat(timespec="seconds")
    conn.execute("CREATE TABLE IF NOT EXISTS schema_version (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)")
    conn.execute(
        "INSERT INTO schema_version (version, applied_at) VALUES (%s, %s) ON CONFLICT (version) DO NOTHING",
        (version, stamp),
    )


def migrate_postgres(dsn: str) -> int:
    """Apply shared SQL (rewritten) + `.pg.sql` triggers. Version recorded only after commit."""
    conn = connect_postgres(dsn)
    try:
        check_schema_pg(conn)
        applied = current_version_pg(conn)
        dialect = {version_of(f): f for f in list_dialect_files("pg")}
        pending = [f for f in list_migration_files() if version_of(f) > applied]
        for path in pending:
            conn.execute("BEGIN")
            try:
                _apply_sql_pg(conn, rewrite_sql_for_postgres(path.read_text(encoding="utf-8")))
                extra = dialect.get(version_of(path))
                if extra is not None:
                    _apply_sql_pg(conn, extra.read_text(encoding="utf-8"))
                _record_version_pg(conn, version_of(path))
                conn.commit()
            except Exception:
                conn.rollback()
                raise
        ver = current_version_pg(conn)
        if ver == 0:
            conn.execute("BEGIN")
            _record_version_pg(conn, 0)
            conn.commit()
        return current_version_pg(conn)
    finally:
        conn.close()


def health_ping(dsn: str) -> dict[str, Any]:
    conn = connect_postgres(dsn)
    try:
        row = conn.execute("SELECT 1 AS ok").fetchone()
        if row is None or int(row["ok"]) != 1:
            raise StoreConfigError("postgres health ping failed")
        return {"ok": True, "engine": "postgres", "schema_version": current_version_pg(conn)}
    finally:
        conn.close()


class PostgresTransaction:
    def __init__(self, store: PostgresLedgerStore) -> None:
        self.store = store

    def __enter__(self) -> PostgresTransaction:  # noqa: PYI034
        if self.store._in_txn:
            raise RuntimeError("nested transaction")
        self.store._in_txn = True
        self.store.conn.execute("BEGIN")
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: object,
    ) -> None:
        try:
            if exc_type is not None:
                self.store.conn.rollback()
            else:
                self.store.conn.commit()
        finally:
            self.store._in_txn = False


class PostgresLedgerStore:
    """V2 store on Postgres. Same LedgerStore surface as SqliteLedgerStore for dual-engine CI."""

    def __init__(self, dsn: str, *, migrate_schema: bool = False, role: str = "engine") -> None:
        if not is_postgres_dsn(dsn):
            raise StoreConfigError("postgres engine requires STATE_DSN")
        if migrate_schema:
            migrate_postgres(dsn)
        self.dsn = dsn
        self.role = role
        self._in_txn = False
        self._seq = 0
        self.conn = connect_postgres(dsn)
        self.schema_version = check_schema_pg(self.conn)
        ping = self.conn.execute("SELECT 1 AS ok").fetchone()
        if ping is None or int(ping["ok"]) != 1:
            self.conn.close()
            raise StoreConfigError("postgres health ping failed")

    def close(self) -> None:
        self.conn.close()

    def transaction(self) -> PostgresTransaction:
        return PostgresTransaction(self)

    def health_ping(self) -> dict[str, Any]:
        row = self.conn.execute("SELECT 1 AS ok").fetchone()
        if row is None or int(row["ok"]) != 1:
            raise StoreConfigError("postgres health ping failed")
        return {"ok": True, "engine": "postgres", "schema_version": self.schema_version}

    def checkpoint(self, envelope: CheckpointEnvelope) -> None:
        if not self._in_txn:
            raise RuntimeError("checkpoint outside transaction")
        self._seq += 1
        stamp = iso_ist()
        session = datetime.fromisoformat(envelope.available_ts).astimezone(IST).date().isoformat()
        self.conn.execute(
            "INSERT INTO engine_checkpoint (role, stream, last_entry_id, input_seq, session, updated_at) "
            "VALUES (%s, %s, %s, %s, %s, %s) ON CONFLICT (role, stream) DO UPDATE SET "
            "last_entry_id=EXCLUDED.last_entry_id, input_seq=EXCLUDED.input_seq, "
            "session=EXCLUDED.session, updated_at=EXCLUDED.updated_at",
            (self.role, envelope.stream, envelope.event_id, self._seq, session, stamp),
        )
        self.enqueue_outbox(envelope)

    def get_last_checkpoint(self) -> tuple[str, str] | None:
        row = self.conn.execute(
            "SELECT last_entry_id, updated_at FROM engine_checkpoint WHERE role=%s ORDER BY input_seq DESC LIMIT 1",
            (self.role,),
        ).fetchone()
        return (row["last_entry_id"], row["updated_at"]) if row else None

    def enqueue_outbox(self, envelope: CheckpointEnvelope) -> None:
        payload = {
            "event_id": envelope.event_id,
            "event_type": envelope.event_type,
            "available_ts": envelope.available_ts,
            "payload": envelope.payload,
        }
        import json

        self.conn.execute(
            "INSERT INTO outbox (event_id, stream, envelope_json, created_at) VALUES (%s, %s, %s, %s) "
            "ON CONFLICT (event_id) DO NOTHING",
            (envelope.event_id, envelope.stream, json.dumps(payload, sort_keys=True), iso_ist()),
        )

    def drain_outbox(self) -> list[dict[str, Any]]:
        rows = list(self.conn.execute("SELECT * FROM outbox WHERE published_at IS NULL ORDER BY seq"))
        stamp = iso_ist()
        out: list[dict[str, Any]] = []
        for r in rows:
            rec = dict(r)
            self.conn.execute("UPDATE outbox SET published_at=%s WHERE seq=%s", (stamp, rec["seq"]))
            out.append(rec)
        return out

    def upsert_position_v2(
        self,
        account_id: str,
        instrument_id: str,
        net_qty: int,
        avg_price: Decimal | float | str,
        *,
        strategy_id: str | None = None,
        exit_plan_json: str | None = None,
        opened_at: str | None = None,
    ) -> None:
        stamp = iso_ist()
        self.conn.execute(
            "INSERT INTO positions_v2 (account_id, instrument_id, net_qty, avg_price, opened_at, "
            "strategy_id, exit_plan_json, updated_at) VALUES (%s, %s, %s, %s, %s, %s, %s, %s) "
            "ON CONFLICT (account_id, instrument_id) DO UPDATE SET net_qty=EXCLUDED.net_qty, "
            "avg_price=EXCLUDED.avg_price, strategy_id=EXCLUDED.strategy_id, "
            "exit_plan_json=EXCLUDED.exit_plan_json, updated_at=EXCLUDED.updated_at",
            (
                account_id,
                instrument_id,
                net_qty,
                money_sql(avg_price),
                opened_at or stamp,
                strategy_id,
                exit_plan_json,
                stamp,
            ),
        )

    def positions_v2(self) -> list[dict[str, Any]]:
        return [dict(r) for r in self.conn.execute("SELECT * FROM positions_v2 WHERE net_qty != 0")]


def open_ledger_store(*, migrate_schema: bool = False, config: StoreConfig | None = None) -> Any:
    cfg = config if config is not None else load_store_config()
    if cfg.engine == "postgres":
        return PostgresLedgerStore(cfg.dsn, migrate_schema=migrate_schema)
    from ledger.v2 import SqliteLedgerStore

    return SqliteLedgerStore(cfg.sqlite_path, migrate_schema=migrate_schema)
