"""V2-23 fail-closed JWT + C5-02 paper login. Paper only. No live orders."""

from auth.foundation import (
    ACCESS_TTL_S,
    AUD,
    COMMAND_PER_S,
    CUSTOMER_CHANNELS,
    CUSTOMER_SIGNAL_FIELDS,
    FOUNDER_CHANNELS,
    ISS,
    PAPER_CUSTOMER_CAP,
    PAPER_IDENTITY_CAP,
    REFRESH_TTL_S,
    REST_PER_S,
    WS_SUBSCRIBE_PER_S,
    AuthClosed,
    AuthDecision,
    AuthRateLimiter,
    TokenPair,
    allow_channel,
    authorize_control,
    channels_for,
    customer_safe,
    encode_jwt,
    issue_access,
    issue_pair,
    issue_refresh,
    looks_like_jwt,
    refresh_to_access,
    totp_at,
    verify_access,
    verify_jwt,
    verify_totp,
)
from auth.keys import load_jwt_secret, require_jwt_secret
from auth.login import PAPER_CUSTOMERS_ENV, login, paper_customer_allowlist, refresh_session

__all__ = [
    "ACCESS_TTL_S",
    "AUD",
    "COMMAND_PER_S",
    "CUSTOMER_CHANNELS",
    "CUSTOMER_SIGNAL_FIELDS",
    "FOUNDER_CHANNELS",
    "ISS",
    "PAPER_CUSTOMER_CAP",
    "PAPER_CUSTOMERS_ENV",
    "PAPER_IDENTITY_CAP",
    "REFRESH_TTL_S",
    "REST_PER_S",
    "WS_SUBSCRIBE_PER_S",
    "AuthClosed",
    "AuthDecision",
    "AuthRateLimiter",
    "TokenPair",
    "allow_channel",
    "authorize_control",
    "channels_for",
    "customer_safe",
    "encode_jwt",
    "issue_access",
    "issue_pair",
    "issue_refresh",
    "load_jwt_secret",
    "login",
    "looks_like_jwt",
    "paper_customer_allowlist",
    "refresh_session",
    "refresh_to_access",
    "require_jwt_secret",
    "totp_at",
    "verify_access",
    "verify_jwt",
    "verify_totp",
]
